name: jungle-wilds # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title:  Jungle Wilds Adventure
summary: Master the art of jungle survival!
description: Gather resources, craft weapons, and uncover hidden paths while facing dangerous animals and rival explorers.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  jungle-wilds:
    command: bin/jungle-wilds-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  jungle-wilds:
    plugin: dump
    source: .
    organize:
      jungle-wilds-bin: bin/
